<a href="https://colab.research.google.com/github/magdoch/ML_python_projects/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_C%D0%BE%D1%80%D0%BE%D0%BA%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
import numpy as np

In [23]:
v= np.random.rand((10))
print(f"Вектор розміром {v.shape}:\n{v}")

Вектор розміром (10,):
[0.50832304 0.41081889 0.56891178 0.04589681 0.99329461 0.38527046
 0.50859564 0.5681217  0.33475226 0.03071487]


In [21]:
m= np.array([[11, 14, 17],
            [20, 23, 26],
             [29,32,35]])
print(f"Матриця розміром {m.shape}:\n {m}")

Матриця розміром (3, 3):
 [[11 14 17]
 [20 23 26]
 [29 32 35]]  



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [29]:
v_mult_const = np.round(v + 10, 2)
print(f"Вектор після додавання 10 і округлення до 2 знаків:\n {v_mult_const}")


Вектор після додавання 10 і округлення до 2 знаків:
 [10.51 10.41 10.57 10.05 10.99 10.39 10.51 10.57 10.33 10.03]


In [30]:
m_mult_const = 2 * m
print(f"Матриця після множення на константу 2:\n {v_mult_const}")

Матриця після множення на константу 2:
 [10.51 10.41 10.57 10.05 10.99 10.39 10.51 10.57 10.33 10.03]


In [36]:
squared_vector = v ** 2
upgrade_squared_vector = v_mult_const ** 2
print(f"Вектор квадратів початкового:\n {squared_vector}")
print(f"\nВектор квадратів оноленого :\n {upgrade_squared_vector}")

Вектор квадратів початкового:
 [2.58392312e-01 1.68772157e-01 3.23660613e-01 2.10651694e-03
 9.86634189e-01 1.48433324e-01 2.58669526e-01 3.22762267e-01
 1.12059074e-01 9.43403281e-04]

Вектор квадратів оноленого :
 [110.4601 108.3681 111.7249 101.0025 120.7801 107.9521 110.4601 111.7249
 106.7089 100.6009]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [38]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [46]:
result_matrix = np.dot(B,A)
print(f"Результат множення двох матриць B,A в розмірі {result_matrix.shape}:\n{result_matrix}")
#я так розумію, що нам ж ніхто не заброняє поміняти їх місцями при множені, бо це не вказано в умові тому, щоб отримати заданий розмір я зробила це

Результат множення двох матриць B,A в розмірі (2, 2):
[[0.7281 0.5202]
 [0.2034 0.2846]]


In [48]:
mult_vector_matrix = np.dot(result_matrix,C)
print(f"Результат множення матриці result_matrix на вектор C:\n{mult_vector_matrix}")

Результат множення матриці result_matrix на вектор C:
[[0.5202]
 [0.2846]]


In [49]:
mult_matrixs = np.dot(result_matrix,D)
print(f"Результат множення матриці result_matrix на матрицю D:\n{mult_matrixs}")

Результат множення матриці result_matrix на матрицю D:
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [50]:
t_matrix = result_matrix.T

In [78]:
t_vector = v.T

In [69]:
print(f"Транспонована матриця:\n{t_matrix} ")
print(f"\nОригінальний вектор:\n {v} ")
print(f"\nТранспонований вектор:\n{t_vector} ")

Транспонована матриця:
[[0.7281 0.2034]
 [0.5202 0.2846]] 

Оригінальний вектор:
 [0.50832304 0.41081889 0.56891178 0.04589681 0.99329461 0.38527046
 0.50859564 0.5681217  0.33475226 0.03071487] 

Транспонований вектор:
[0.50832304 0.41081889 0.56891178 0.04589681 0.99329461 0.38527046
 0.50859564 0.5681217  0.33475226 0.03071487] 


Змін вектора немає через форму (n,)

In [70]:
column_vector = np.expand_dims(v, axis=1)
print(f"Змінений вектор:\n{column_vector}")

Змінений вектор:
[[0.50832304]
 [0.41081889]
 [0.56891178]
 [0.04589681]
 [0.99329461]
 [0.38527046]
 [0.50859564]
 [0.5681217 ]
 [0.33475226]
 [0.03071487]]


In [72]:
t_col_v = column_vector.T
print(f"\nТранспонований вектор:\n{t_col_v} ")


Транспонований вектор:
[[0.50832304 0.41081889 0.56891178 0.04589681 0.99329461 0.38527046
  0.50859564 0.5681217  0.33475226 0.03071487]] 


Тут ми маємо тепер зміну форми на (1, n)

In [76]:
#зробила ще таке з вектором С
t1_vector = C.T

In [77]:
print(f"Транспонована матриця:\n{t_matrix} ")
print(f"\nОригінальний вектор:\n {C} ")
print(f"\nТранспонований вектор:\n{t1_vector} ")


Транспонована матриця:
[[0.7281 0.2034]
 [0.5202 0.2846]] 

Оригінальний вектор:
 [[0]
 [1]] 

Транспонований вектор:
[[0 1]] 


In [74]:
column_vector1 = np.expand_dims(C, axis=1)
print(f"Змінений вектор:\n{column_vector1}")


Змінений вектор:
[[[0]]

 [[1]]]


In [73]:
t1_col_v = column_vector1.T
print(f"\nТранспонований вектор:\n{t1_col_v} ")



Транспонований вектор:
[[[0 1]]] 
